-- | Core types and functions for LLM operations
module LLM.Core
  ( LLMGateway (..),
    ChatRequest (..),
    ChatResponse (..),
    mkChatResponse,
    LLMTextResult,
    LLMObjectResult,
    LLMResult,
    LLMError (..),
    Turn (..),
    pattern UserTurn,
    ContentPart (..),
    PartBody (..),
    CacheHint (..),
    ImageSource (..),
    ThinkingContent (..),
    ProviderOpaque (..),
    textPart,
    thinkingPart,
    toolCallPart,
    imageUrlPart,
    imageBase64Part,
    withCacheHint,
    cacheEphemeral,
    mkImageBase64,
    supportedImageMediaTypes,
    projectText,
    projectReasoning,
    turnToolCalls,
    conversationHasImages,
    coalesceAdjacentTextParts,
    validateTurn,
    ToolCall (..),
    ToolResult (..),
    LLMHooks (..),
    TypedTool (..),
    ToolDef (..),
    StreamEvent (..),
    ThinkingMode (..),
    MessageEncodeOptions (..),
    defaultMessageEncodeOptions,
    deepSeekMessageEncodeOptions,
    assistantTurn,
    Usage (..),
    PricingInfo (..),
    emptyUsage,
    mkUsage,
    addUsage,
    estimateCost,
    usageOrdinaryInputTokens,
    defaultPricingInfo,
    AbortSignal,
    newAbortSignal,
    abort,
    isAborted,
    isAbortedMaybe,
    LLMProvider (..),
    hasToolCalls,
    getToolCalls,
    toolResult,
  )
where

import LLM.Core.Abort
import LLM.Core.LLMProvider
import LLM.Core.Types
import LLM.Core.Usage
import LLM.Core.Utils
