module LLM
  ( -- * Core conversation types
    Turn (..),
    ToolCall (..),
    ToolResult (..),
    ToolDef (..),
    TypedTool (..),
    ChatResponse (..),
    ContentBlock (..),
    LLMGateway (..),
    LLMError (..),
    Usage (..),
    PricingInfo (..),
    emptyUsage,
    addUsage,
    estimateCost,
    ThinkingMode (..),
    LLMHooks (..),
    AbortSignal,
    getToolCalls,

    -- * Single-shot generation
    generateTextWithFallbacks,
    streamTextWithFallbacks,
    genObject,
    genObjectUntyped,
    ModelConfig (..),
    ModelWithFallbacks (..),
    GenRequest (..),
    GenerateResult,
    GenerateError (..),
    GenerateErrorResult (..),
    GenerateTextResult (..),
    StreamChunk (..),
    RoundTextRole (..),
    GeneratableObject,
    Hooks (..),
    noHooks,
    llmHooks,
    defaultDebugHooks,
    debugHooks,

    -- * Agent and tool building blocks
    Agent (..),
    RuntimeArgs (..),
    Tool (..),
    ToolContext (..),
    createGenRequest,
    toTool,
    GenerateEvent (..),
    GenerateEventDetail (..),
    EventObserver,
    noEventObserver,

    -- * Model catalog and filesystem tool wiring
    loadModelOrThrow,
    loadModelsOrThrow,
    LoadConfigError (..),
    loadModelCatalog,
    ModelCatalogItem (..),
    ModelCatalogMap,
    fsTools,
    fsTools',
  )
where

import LLM.Agent
  ( Agent (..),
    EventObserver,
    GenerateEvent (..),
    GenerateEventDetail (..),
    RuntimeArgs (..),
    Tool (..),
    ToolContext (..),
    createGenRequest,
    noEventObserver,
    toTool,
  )
import LLM.Core
  ( AbortSignal,
    ChatResponse (..),
    ContentBlock (..),
    LLMError (..),
    LLMGateway (..),
    LLMHooks (..),
    PricingInfo (..),
    ThinkingMode (..),
    ToolCall (..),
    ToolDef (..),
    ToolResult (..),
    Turn (..),
    TypedTool (..),
    Usage (..),
    addUsage,
    emptyUsage,
    estimateCost,
    getToolCalls,
  )
import LLM.Generate
  ( GenRequest (..),
    GenerateError (..),
    GenerateErrorResult (..),
    GenerateResult,
    GenerateTextResult (..),
    GeneratableObject,
    Hooks (..),
    ModelConfig (..),
    ModelWithFallbacks (..),
    StreamChunk (..),
    RoundTextRole (..),
    debugHooks,
    defaultDebugHooks,
    genObject,
    genObjectUntyped,
    generateTextWithFallbacks,
    llmHooks,
    noHooks,
    streamTextWithFallbacks,
  )
import LLM.Load
  ( LoadConfigError (..),
    ModelCatalogItem (..),
    ModelCatalogMap,
    fsTools,
    fsTools',
    loadModelCatalog,
    loadModelOrThrow,
    loadModelsOrThrow,
  )
